### ISSUE TITLE
`enter.{c}sh` should not do poetry update when entering dev env if lock file exists

### ISSUE THREAD

**Issue by hintron** [evillase/py_project_template#6]
See https://github.com/intel-innersource/applications.productivity.bootstrap-virtual-environment/issues/19 for explanation of the issue. Simply put, we should remove the `poetry update` when a lock file is detected, or else brand-new repo cloners will end up updating their packages instead of reproducing a stable environment based on the lock file.

**Comment by evillase** [comment]
good job finding it. i forgot it started here. i thought we made them new in the tlt repo.

Doing a read through the poetry docs:
https://python-poetry.org/docs/cli/#update
https://python-poetry.org/docs/cli/#install

I believe the behavior as coded is almost correct.
The cases are as follows:

- The project.toml file specifies a package version.
  - There exists a lock file, update will bring it up to date to the latest allowed versions in project.toml
  - There does not exist a lock file, install should create one.
    - Not update
    - it should also install the package
